version: '3'
services:
  transmission:
    build:
      context: ..
      dockerfile: docker/transmission.df
  testbed:
    build:
      context: ..
      dockerfile: docker/clutch.df
    depends_on:
      - transmission
  start_dependencies:
    build:
      context: .
      dockerfile: integration-wait.df
    depends_on:
      - transmission
    command: transmission:9091
